//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public class radioactivity : MonoBehaviour {
	public float rdlevel;
	void Awake () {
		rdlevel = 0f;
	}
	void Update () {
		/*
		if(radioactivity >= 100){
			player dies.
			display time.
			Application.Loadlevel("Main Menu");
		}
		*/
	}
}

